//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool from CryptoGateway Software Inc.
//     Tool name: CGW X-Script RDB visual Layer Generator
//
//     Archymeta Information Technologies Co., Ltd.
//
//     Changes to this file, could be overwritten if the code is re-generated.
//     Add (if not yet) a code-manager node to the generator to specify 
//     how existing files are processed.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace CryptoGateway.RDB.Data.MembershipPlus
{
    /// <summary>
    /// A entity in "NotificationTaskSchedules" data set.
    /// </summary>
    /// <remarks>
    ///  <para>
    ///    Properties of the entity are categorized in the following:
    ///  </para>
    ///  <list type="table">
    ///    <listheader>
    ///       <term>Primary keys</term><description>Description</description>
    ///    </listheader>
    ///    <item>
    ///      <term>EventID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.EventID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///    <item>
    ///      <term>NotificationID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.NotificationID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///  </list>
    ///  <list type="table">
    ///    <listheader>
    ///       <term>Intrinsic Identifiers</term><description>Description</description>
    ///    </listheader>
    ///    <item>
    ///      <term>EventID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.EventID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///    <item>
    ///      <term>NotificationID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.NotificationID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///  </list>
    ///  <list type="table">
    ///    <listheader>
    ///       <term>None editable properties</term><description>Description</description>
    ///    </listheader>
    ///    <item>
    ///      <term>AssignDate</term>
    ///      <description>See <see cref="NotificationTaskSchedule.AssignDate" />. Fixed; not null.</description>
    ///    </item>
    ///  </list>
    ///  <list type="table">
    ///    <listheader>
    ///       <term>Foreign keys</term><description>Description</description>
    ///    </listheader>
    ///    <item>
    ///      <term>EventID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.EventID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///    <item>
    ///      <term>NotificationID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.NotificationID" />. Primary key; intrinsic id; fixed; not null; foreign key.</description>
    ///    </item>
    ///    <item>
    ///      <term>AssignerID</term>
    ///      <description>See <see cref="NotificationTaskSchedule.AssignerID" />. Fixed; nullable; foreign key.</description>
    ///    </item>
    ///  </list>
    ///  <list type="table">
    ///    <listheader>
    ///       <term>This entity depends on</term><description>Description</description>
    ///    </listheader>
    ///    <item>
    ///      <term>EventCalendarRef</term>
    ///      <description>See <see cref="NotificationTaskSchedule.EventCalendarRef" />, which is a member of the data set "EventCalendar" for <see cref="EventCalendar" />.</description>
    ///    </item>
    ///    <item>
    ///      <term>MemberNotificationRef</term>
    ///      <description>See <see cref="NotificationTaskSchedule.MemberNotificationRef" />, which is a member of the data set "MemberNotifications" for <see cref="MemberNotification" />.</description>
    ///    </item>
    ///    <item>
    ///      <term>UserRef</term>
    ///      <description>See <see cref="NotificationTaskSchedule.UserRef" />, which is a member of the data set "Users" for <see cref="User" />. Nullable.</description>
    ///    </item>
    ///  </list>
    /// </remarks>
    [DataContract]
    public class NotificationTaskSchedule : IDbEntity 
    {
        /// <summary>
        /// For internal use only.
        /// </summary>
        public bool IsOperationHandled = false;

        /// <summary>
        /// Used on the server side to return an unique key for caching purposes.
        /// </summary>
        public string CacheKey
        {
            get
            {
                return this.EventID + ":" + this.NotificationID;
            }
        }

        /// <summary>
        /// Whether or not the entity was already persisted into to the data source. 
        /// </summary>
        [DataMember]
        public bool IsPersisted
        {
            get { return _isPersisted; }
            set { _isPersisted = value; }
        }
        private bool _isPersisted = false;

        /// <summary>
        /// Used internally.
        /// </summary>
        public bool IsInitializing
        {
            get { return _isInitializing; }
            set { _isInitializing = value; }
        }
        private bool _isInitializing = false;

        /// <summary>
        /// Used to matching entities in input adding or updating entity list and the returned ones, see <see cref="INotificationTaskScheduleService.AddOrUpdateEntities" />.
        /// </summary>
        [DataMember]
        public int UpdateIndex
        {
            get { return _updateIndex; }
            set { _updateIndex = value; }
        }
        private int _updateIndex = -1;

        /// <summary>
        /// Configured at system generation step, its value provides a short, but characteristic summary of the entity.
        /// </summary>
        [DataMember]
        public string DistinctString
        {
            get 
            {
                if (_distinctString == null)
                    _distinctString = GetDistinctString(true);
                return _distinctString;
            }
            set
            {
                _distinctString = value;
            }
        }
        private string _distinctString = null;

        private string GetDistinctString(bool ShowPathInfo)
        {
            LoadEventCalendarRef();
            LoadMemberNotificationRef();
            return String.Format(@"{0} task {1}", (EventCalendarRef != null ? EventCalendarRef.DistinctString : ""), (MemberNotificationRef != null ? MemberNotificationRef.DistinctString : ""));
        }

        /// <summary>
        /// Whether or not the entity was edited.
        /// </summary>
        [DataMember]
        public bool IsEntityChanged
        {
            get { return _isEntityChanged; }
            set { _isEntityChanged = value; }
        }
        private bool _isEntityChanged = true;

        /// <summary>
        /// Whether or not the entity was to be deleted.
        /// </summary>
        [DataMember]
        public bool IsDeleted
        {
            get { return _isDeleted; }
            set { _isDeleted = value; }
        }
        private bool _isDeleted = false;

#region Properties of the current entity

        /// <summary>
        /// Meta-info: primary key; intrinsic id; fixed; not null; foreign key.
        /// </summary>
        [Key]
        [Editable(false)]
        [DataMember(IsRequired = true)]
        public string EventID
        { 
            get
            {
                return _EventID;
            }
            set
            {
                if (_EventID != value)
                {
                    _EventID = value;
                }
            }
        }
        private string _EventID = default(string);

        /// <summary>
        /// Meta-info: primary key; intrinsic id; fixed; not null; foreign key.
        /// </summary>
        [Key]
        [Editable(false)]
        [DataMember(IsRequired = true)]
        public string NotificationID
        { 
            get
            {
                return _NotificationID;
            }
            set
            {
                if (_NotificationID != value)
                {
                    _NotificationID = value;
                }
            }
        }
        private string _NotificationID = default(string);

        /// <summary>
        /// Meta-info: fixed; not null.
        /// </summary>
        [Required]
        [Editable(false)]
        [DataMember(IsRequired = true)]
        public DateTime AssignDate
        { 
            get
            {
                return _AssignDate;
            }
            set
            {
                if (_AssignDate != value)
                {
                    _AssignDate = value;
                }
            }
        }
        private DateTime _AssignDate = default(DateTime);

        /// <summary>
        /// Meta-info: fixed; nullable; foreign key.
        /// </summary>
        [Editable(false)]
        [DataMember(IsRequired = false)]
        public string AssignerID
        { 
            get
            {
                return _AssignerID;
            }
            set
            {
                if (_AssignerID != value)
                {
                    _AssignerID = value;
                }
            }
        }
        private string _AssignerID = default(string);

#endregion

#region Entities that the current one depends upon.

        /// <summary>
        /// Entity in data set "EventCalendar" for <see cref="EventCalendar" /> that this entity depend upon through .
        /// The corresponding foreign key set is { <see cref="NotificationTaskSchedule.EventID" /> }.
        /// </summary>
        [DataMember]
        public EventCalendar EventCalendarRef
        {
            get 
            {
                if (_EventCalendarRef == null && AutoLoadEventCalendarRef != null)
                    _EventCalendarRef = AutoLoadEventCalendarRef();
                return _EventCalendarRef; 
            }
            set 
            { 
                _EventCalendarRef = value; 
            }
        }
        private EventCalendar _EventCalendarRef = null;

        /// <summary>
        /// <see cref="NotificationTaskSchedule.EventCalendarRef" /> is not initialized when the entity is created. Clients could call this method to load it provided a proper delegate <see cref="NotificationTaskSchedule.DelLoadEventCalendarRef" /> was setup
        /// before calling it.
        /// </summary>
        public void LoadEventCalendarRef()
        {
            if (_EventCalendarRef != null)
                return;
            if (DelLoadEventCalendarRef != null)
                _EventCalendarRef = DelLoadEventCalendarRef();
        }

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.EventCalendarRef" />.
        /// </summary>
        public Func<EventCalendar> DelLoadEventCalendarRef = null;

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.EventCalendarRef" /> automatically when it is referred to at the first time.
        /// </summary>
        public Func<EventCalendar> AutoLoadEventCalendarRef = null;

        /// <summary>
        /// Entity in data set "MemberNotifications" for <see cref="MemberNotification" /> that this entity depend upon through .
        /// The corresponding foreign key set is { <see cref="NotificationTaskSchedule.NotificationID" /> }.
        /// </summary>
        [DataMember]
        public MemberNotification MemberNotificationRef
        {
            get 
            {
                if (_MemberNotificationRef == null && AutoLoadMemberNotificationRef != null)
                    _MemberNotificationRef = AutoLoadMemberNotificationRef();
                return _MemberNotificationRef; 
            }
            set 
            { 
                _MemberNotificationRef = value; 
            }
        }
        private MemberNotification _MemberNotificationRef = null;

        /// <summary>
        /// <see cref="NotificationTaskSchedule.MemberNotificationRef" /> is not initialized when the entity is created. Clients could call this method to load it provided a proper delegate <see cref="NotificationTaskSchedule.DelLoadMemberNotificationRef" /> was setup
        /// before calling it.
        /// </summary>
        public void LoadMemberNotificationRef()
        {
            if (_MemberNotificationRef != null)
                return;
            if (DelLoadMemberNotificationRef != null)
                _MemberNotificationRef = DelLoadMemberNotificationRef();
        }

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.MemberNotificationRef" />.
        /// </summary>
        public Func<MemberNotification> DelLoadMemberNotificationRef = null;

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.MemberNotificationRef" /> automatically when it is referred to at the first time.
        /// </summary>
        public Func<MemberNotification> AutoLoadMemberNotificationRef = null;

        /// <summary>
        /// Entity in data set "Users" for <see cref="User" /> that this entity depend upon through .
        /// The corresponding foreign key set is { <see cref="NotificationTaskSchedule.AssignerID" /> }.
        /// </summary>
        [DataMember]
        public User UserRef
        {
            get 
            {
                if (AssignerID == null)
                    return null;
                else if (_UserRef == null && AutoLoadUserRef != null)
                    _UserRef = AutoLoadUserRef();
                return _UserRef; 
            }
            set 
            { 
                _UserRef = value; 
            }
        }
        private User _UserRef = null;

        /// <summary>
        /// <see cref="NotificationTaskSchedule.UserRef" /> is not initialized when the entity is created. Clients could call this method to load it provided a proper delegate <see cref="NotificationTaskSchedule.DelLoadUserRef" /> was setup
        /// before calling it.
        /// </summary>
        public void LoadUserRef()
        {
            if (AssignerID == null || _UserRef != null)
                return;
            if (DelLoadUserRef != null)
                _UserRef = DelLoadUserRef();
        }

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.UserRef" />.
        /// </summary>
        public Func<User> DelLoadUserRef = null;

        /// <summary>
        /// A delegate to load <see cref="NotificationTaskSchedule.UserRef" /> automatically when it is referred to at the first time.
        /// </summary>
        public Func<User> AutoLoadUserRef = null;

#endregion

#region Entities that depend on the current one.

#endregion

        /// <summary>
        /// Whether or not the present entity is identitical to <paramref name="other" />, in the sense that they have the same (set of) primary key(s).
        /// </summary>
        /// <param name="other">The entity to be compared to.</param>
        /// <returns>
        ///   The result of comparison.
        /// </returns>
        public bool IsEntityIdentical(NotificationTaskSchedule other)
        {
            if (other == null)
                return false;
            if (EventID != other.EventID)
                return false;
            if (NotificationID != other.NotificationID)
                return false;
            return true;
        }              

        /// <summary>
        /// Whether or not the present entity is identitical to <paramref name="other" />, in the sense that they have the same (set of) intrinsic identifiers.
        /// </summary>
        /// <param name="other">The entity to be compared to.</param>
        /// <returns>
        ///   The result of comparison.
        /// </returns>
        public bool IsEntityTheSame(NotificationTaskSchedule other)
        {
            if (other == null)
                return false;
            else
                return EventID == other.EventID &&  NotificationID == other.NotificationID;
        }              

        /// <summary>
        /// Merge changes inside entity <paramref name="from" /> to the entity <paramref name="to" />. Any changes in <paramref name="from" /> that is not changed in <paramref name="to" /> is updated inside <paramref name="to" />.
        /// </summary>
        /// <param name="from">The "old" entity acting as merging source.</param>
        /// <param name="to">The "new" entity which inherits changes made in <paramref name="from" />.</param>
        /// <returns>
        /// </returns>
        public static void MergeChanges(NotificationTaskSchedule from, NotificationTaskSchedule to)
        {
            if (to.IsPersisted)
            {
            }
            else
            {
                to.IsPersisted = from.IsPersisted;
                to.EventID = from.EventID;
                to.NotificationID = from.NotificationID;
                to.AssignDate = from.AssignDate;
                to.AssignerID = from.AssignerID;
            }
        }

        /// <summary>
        /// Update changes to the current entity compared to an input <paramref name="newdata" /> and set the entity to a proper state for updating.
        /// </summary>
        /// <param name="newdata">The "new" entity acting as the source of the changes, if any.</param>
        /// <returns>
        /// </returns>
        public void UpdateChanges(NotificationTaskSchedule newdata)
        {
            int cnt = 0;
            IsEntityChanged = cnt > 0;
        }

        /// <summary>
        /// Internal use
        /// </summary>
        public void NormalizeValues()
        {
            IsInitializing = true;
            IsInitializing = false;
        }

        /// <summary>
        /// Internal use
        /// </summary>
        public NotificationTaskSchedule ShallowCopy(bool allData = false)
        {
            NotificationTaskSchedule e = new NotificationTaskSchedule();
            e.IsInitializing = true;
            e.EventID = EventID;
            e.NotificationID = NotificationID;
            e.AssignDate = AssignDate;
            e.AssignerID = AssignerID;
            e.DistinctString = GetDistinctString(true);
            e.IsPersisted = true;
            e.IsEntityChanged = false;
            e.IsInitializing = false;
            return e;
        }

        /// <summary>
        /// A textual representation of the entity.
        /// </summary>
        public override string ToString()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.Append(@"
----===== [[NotificationTaskSchedule]] =====----
  EventID = '" + EventID + @"'");
            sb.Append(@" (natural id)");
            sb.Append(@"
  NotificationID = '" + NotificationID + @"'");
            sb.Append(@" (natural id)");
            sb.Append(@"
  AssignDate = " + AssignDate + @"
  AssignerID = '" + (AssignerID != null ? AssignerID : "null") + @"'
");
            return sb.ToString();
        }

    }

    ///<summary>
    ///The result of an add or update of type <see cref="NotificationTaskSchedule" />.
    ///</summary>
    [DataContract]
    public class NotificationTaskScheduleUpdateResult : IUpdateResult
    {
        /// <summary>
        /// Status of add, update or delete operation
        /// </summary>
        [DataMember]
        public int OpStatus
        {
            get { return _opStatus; }
            set { _opStatus = value; }
        }
        private int _opStatus = (int)EntityOpStatus.Unknown;

        /// <summary>
        /// Parents or child operation status
        /// </summary>
        [DataMember]
        public int RelatedOpStatus
        {
            get { return _relatedOpStatus; }
            set { _relatedOpStatus = value; }
        }
        private int _relatedOpStatus = (int)EntityOpStatus.Unknown;

        /// <summary>
        /// The updated entity.
        /// </summary>
        [DataMember]
        public NotificationTaskSchedule UpdatedItem
        {
            get;
            set;
        }

        /// <summary>
        /// If the relational data source has a way of detecting concurrent update conflicts, this is the item inside the
        /// data source that had been updated by other agents in between the load and update time interval of the present
        /// agent. The client software should resolve the conflict.
        /// </summary>
        [DataMember]
        public NotificationTaskSchedule ConflictItem
        {
            get;
            set;
        }

        /// <summary>
        /// String representation of the entity.
        /// </summary>
        public string EntityInfo 
        { 
            get { return UpdatedItem == null ? "NULL" : UpdatedItem.ToString(); }
        }
    }

}
